import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e2e2",
        "surface-container-highest": "#e2e2e2",
        "outline-variant": "#c0c8c9",
        "on-primary-fixed": "#001f23",
        "on-tertiary-container": "#c59377",
        tertiary: "#361805",
        "primary-container": "#0d3b40",
        "on-background": "#1a1c1c",
        "primary-fixed": "#bfeaf0",
        "inverse-surface": "#2f3131",
        "on-surface": "#1a1c1c",
        "inverse-primary": "#a3ced4",
        "tertiary-fixed-dim": "#f1bb9c",
        "on-secondary": "#ffffff",
        primary: "#002428",
        outline: "#717879",
        secondary: "#735c00",
        "on-secondary-container": "#745c00",
        "surface-container-low": "#f3f3f3",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        surface: "#f9f9f9",
        "surface-container": "#eeeeee",
        "tertiary-container": "#4f2d17",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#633e27",
        "on-primary-container": "#7ba5ab",
        "surface-dim": "#dadada",
        "on-tertiary-fixed": "#301402",
        "secondary-container": "#fed65b",
        "inverse-on-surface": "#f0f1f0",
        "primary-fixed-dim": "#a3ced4",
        "tertiary-fixed": "#ffdbc8",
        "on-error": "#ffffff",
        background: "#f9f9f9",
        "on-surface-variant": "#414849",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#234d52",
        "surface-tint": "#3c656a",
        "on-secondary-fixed-variant": "#574500",
        "secondary-fixed": "#ffe088",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-padding-lg": "120px",
        unit: "8px",
        "container-max": "1200px",
        "margin-mobile": "20px",
        gutter: "24px",
        "section-padding-md": "80px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        playfair: ["Playfair Display", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
